#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2026 Anupam Sengupta <anupamsg@gmail.com>
#
# Tests for Bangla date conversion helpers and CLI entrypoints.

from __future__ import annotations

import csv
import subprocess
import sys
import unittest
from datetime import date, datetime, timedelta
from pathlib import Path

from bangla_date import (
    BANGLA_MONTHS,
    SEASONS,
    __version__,
    english_to_bangla_digits,
    format_bangla_date,
    format_current_bangla_date,
    gregorian_to_bangla_date,
    ইংরেজি_থেকে_বাংলা_সংখ্যা,
    গ্রেগরিয়ান_থেকে_বাংলা_তারিখ,
)

_REFERENCE_PATH = Path(__file__).with_name("drik_reference.tsv")


def _load_reference() -> list[tuple[date, int, str, int]]:
    rows: list[tuple[date, int, str, int]] = []
    with _REFERENCE_PATH.open(encoding="utf-8") as handle:
        for row in csv.reader(handle, delimiter="\t"):
            if not row or row[0].startswith("#"):
                continue
            year, month, day = (int(part) for part in row[0].split("-"))
            rows.append(
                (date(year, month, day), int(row[1]), BANGLA_MONTHS[int(row[2])], int(row[3]))
            )
    return rows


class BanglaDateTests(unittest.TestCase):
    def test_conversions_match_independent_reference(self) -> None:
        # drik_reference.tsv is generated by tests/generate_drik_reference.py from
        # an independent ephemeris (PyEphem), not from this package.
        for gregorian_date, expected_day, expected_month, expected_year in _load_reference():
            with self.subTest(gregorian_date=gregorian_date.isoformat()):
                bangla_day, bangla_month, bangla_year, bangla_season = gregorian_to_bangla_date(
                    gregorian_date
                )
                self.assertEqual(
                    (bangla_day, bangla_month, bangla_year),
                    (expected_day, expected_month, expected_year),
                )
                self.assertIn(bangla_season, SEASONS)

    def test_bangla_named_alias_matches_english_alias(self) -> None:
        for gregorian_date, _day, _month, _year in _load_reference()[:12]:
            with self.subTest(gregorian_date=gregorian_date.isoformat()):
                self.assertEqual(
                    গ্রেগরিয়ান_থেকে_বাংলা_তারিখ(gregorian_date),
                    gregorian_to_bangla_date(gregorian_date),
                )

    def test_month_lengths_vary_between_years(self) -> None:
        # Drik Siddhanta months range from 29 to 32 days.
        self.assertEqual(gregorian_to_bangla_date(date(2024, 7, 16))[0], 32)
        self.assertEqual(gregorian_to_bangla_date(date(2025, 6, 15))[0], 32)
        self.assertEqual(gregorian_to_bangla_date(date(2026, 8, 17))[0], 32)
        self.assertEqual(gregorian_to_bangla_date(date(2024, 12, 15))[0], 29)

    def test_new_year_boundary_rolls_over_on_boishakh(self) -> None:
        before = gregorian_to_bangla_date(date(2024, 4, 13))
        after = gregorian_to_bangla_date(date(2024, 4, 14))

        self.assertEqual((before[1], before[2]), ("চৈত্র", 1430))
        self.assertEqual((after[1], after[2]), ("বৈশাখ", 1431))

    def test_every_month_maps_to_a_valid_season(self) -> None:
        seen_months = set()
        current = date(2024, 1, 1)
        while current < date(2025, 1, 1):
            bangla_day, bangla_month, _year, bangla_season = gregorian_to_bangla_date(current)
            self.assertGreaterEqual(bangla_day, 1)
            self.assertLessEqual(bangla_day, 32)
            self.assertIn(bangla_season, SEASONS)
            seen_months.add(bangla_month)
            current += timedelta(days=1)

        self.assertEqual(len(seen_months), 12)

    def test_accepts_plain_date(self) -> None:
        self.assertEqual(gregorian_to_bangla_date(date(2024, 4, 14)), (1, "বৈশাখ", 1431, "গ্রীষ্ম"))

    def test_digit_conversion_supports_english_and_bangla_aliases(self) -> None:
        self.assertEqual(english_to_bangla_digits(0), "০")
        self.assertEqual(english_to_bangla_digits(42), "৪২")
        self.assertEqual(ইংরেজি_থেকে_বাংলা_সংখ্যা(1432), "১৪৩২")

    def test_formatter_includes_date_and_season(self) -> None:
        output = format_bangla_date(datetime(2024, 8, 15))

        self.assertIn("আজকের বাংলা তারিখ: ৩০ শ্রাবণ, ১৪৩১ বঙ্গাব্দ", output)
        self.assertIn("বর্তমান ঋতু: বর্ষা", output)

    def test_current_formatter_delegates_to_date_formatter(self) -> None:
        self.assertEqual(
            format_current_bangla_date(datetime(2024, 8, 15)),
            format_bangla_date(datetime(2024, 8, 15)),
        )

    def test_module_cli_prints_expected_sections(self) -> None:
        result = subprocess.run(
            [sys.executable, "-m", "bangla_date"],
            check=True,
            capture_output=True,
            text=True,
        )

        self.assertIn("আজকের বাংলা তারিখ:", result.stdout)
        self.assertIn("বর্তমান ঋতু:", result.stdout)

    def test_module_cli_help_describes_command(self) -> None:
        result = subprocess.run(
            [sys.executable, "-m", "bangla_date", "--help"],
            check=True,
            capture_output=True,
            text=True,
        )

        self.assertIn("Print today's Bangla date and current season.", result.stdout)
        self.assertIn("usage: bangla-date", result.stdout)

    def test_module_cli_reports_version(self) -> None:
        result = subprocess.run(
            [sys.executable, "-m", "bangla_date", "--version"],
            check=True,
            capture_output=True,
            text=True,
        )

        self.assertIn(__version__, result.stdout)

    def test_module_cli_rejects_unknown_arguments(self) -> None:
        result = subprocess.run(
            [sys.executable, "-m", "bangla_date", "--nope"],
            capture_output=True,
            text=True,
        )

        self.assertEqual(result.returncode, 2)
        self.assertIn("unrecognized arguments", result.stderr)

    def test_wrapper_cli_help_matches_module_help(self) -> None:
        result = subprocess.run(
            [sys.executable, "bangla-date.py", "--help"],
            check=True,
            capture_output=True,
            text=True,
        )

        self.assertIn("Print today's Bangla date and current season.", result.stdout)
        self.assertIn("usage: bangla-date", result.stdout)


if __name__ == "__main__":
    unittest.main()
